version: '3.4'

services:
  cssure:
      image: memilnie/cssure:latest
      container_name: cssure_dotnet

      restart: unless-stopped

  python:
      image: memilnie/csi_calculator:latest
      network_mode: bridge
      container_name: cssure_python

      restart: unless-stopped
