version: '3.4'

services:
  cssure:
      image: memilnie/cssure:v1.1dev
      container_name: cssure.dotnet

      restart: unless-stopped

  python:
      image: memilnie/csi_calculator:v2.2Dev
      network_mode: bridge
      container_name: cssure.python

      restart: unless-stopped
