# Define base image
FROM continuumio/miniconda3

# Set working directory for the project
WORKDIR /app

# Create Conda environment from the YAML file
COPY env.yml .
RUN conda env create -n Temo -f env.yml

# Override default shell and use bash
SHELL ["conda", "run", "-n", "Temo", "/bin/bash", "-c"]

# Python program to run in the container
COPY QRSDetector.py .
COPY DataProcces.py .

EXPOSE 1883

ENTRYPOINT ["conda", "run", "-n", "Temo", "python", "DataProcces.py"]